version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Azure.SignalR
    versions:
    - 1.7.0
    - 1.7.1
    - 1.8.0
  - dependency-name: Microsoft.Extensions.ApiDescription.Client
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: NSwag.ApiDescription.Client
    versions:
    - 13.10.1
    - 13.10.2
    - 13.10.3
    - 13.10.4
    - 13.10.5
    - 13.10.6
    - 13.10.7
    - 13.10.8
  - dependency-name: Microsoft.ApplicationInsights.AspNetCore
    versions:
    - 2.16.0
