/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Koudenpa.Mackerel.Api.Client;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing AlertApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AlertApiTests : IDisposable
    {
        private AlertApi instance;

        public AlertApiTests()
        {
            instance = new AlertApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlertApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AlertApi
            //Assert.IsType(typeof(AlertApi), instance, "instance is a AlertApi");
        }

        
        /// <summary>
        /// Test GetAlerts
        /// </summary>
        [Fact]
        public void GetAlertsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? withClosed = null;
            //string nextId = null;
            //decimal? limit = null;
            //var response = instance.GetAlerts(withClosed, nextId, limit);
            //Assert.IsType<AlertsResponse> (response, "response is AlertsResponse");
        }
        
    }

}
