/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Koudenpa.Mackerel.Api.Client;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing HostApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HostApiTests : IDisposable
    {
        private HostApi instance;

        public HostApiTests()
        {
            instance = new HostApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' HostApi
            //Assert.IsType(typeof(HostApi), instance, "instance is a HostApi");
        }

        
        /// <summary>
        /// Test GetHost
        /// </summary>
        [Fact]
        public void GetHostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string hostId = null;
            //var response = instance.GetHost(hostId);
            //Assert.IsType<HostResponse> (response, "response is HostResponse");
        }
        
        /// <summary>
        /// Test GetHosts
        /// </summary>
        [Fact]
        public void GetHostsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string service = null;
            //string role = null;
            //string name = null;
            //string status = null;
            //string customIdentifier = null;
            //var response = instance.GetHosts(service, role, name, status, customIdentifier);
            //Assert.IsType<HostsResponse> (response, "response is HostsResponse");
        }
        
        /// <summary>
        /// Test PostHostStatus
        /// </summary>
        [Fact]
        public void PostHostStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string hostId = null;
            //HostStatusRequest hostStatus = null;
            //var response = instance.PostHostStatus(hostId, hostStatus);
            //Assert.IsType<ApiResponse> (response, "response is ApiResponse");
        }
        
    }

}
