/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Koudenpa.Mackerel.Api.Client;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing ServiceMetricApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ServiceMetricApiTests : IDisposable
    {
        private ServiceMetricApi instance;

        public ServiceMetricApiTests()
        {
            instance = new ServiceMetricApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceMetricApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ServiceMetricApi
            //Assert.IsType(typeof(ServiceMetricApi), instance, "instance is a ServiceMetricApi");
        }

        
        /// <summary>
        /// Test PostServiceMetric
        /// </summary>
        [Fact]
        public void PostServiceMetricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serviceName = null;
            //List<ServiceMetricValue> serviceMetrics = null;
            //var response = instance.PostServiceMetric(serviceName, serviceMetrics);
            //Assert.IsType<ApiResponse> (response, "response is ApiResponse");
        }
        
    }

}
