/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Koudenpa.Mackerel.Api.Client.OpenAPIDateConverter;

namespace Koudenpa.Mackerel.Api.Model
{
    /// <summary>
    /// AlertsResponse
    /// </summary>
    [DataContract]
    public partial class AlertsResponse :  IEquatable<AlertsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsResponse" /> class.
        /// </summary>
        /// <param name="alerts">alerts.</param>
        /// <param name="nextId">nextId.</param>
        public AlertsResponse(List<Alert> alerts = default(List<Alert>), string nextId = default(string))
        {
            this.Alerts = alerts;
            this.NextId = nextId;
        }
        
        /// <summary>
        /// Gets or Sets Alerts
        /// </summary>
        [DataMember(Name="alerts", EmitDefaultValue=false)]
        public List<Alert> Alerts { get; set; }

        /// <summary>
        /// Gets or Sets NextId
        /// </summary>
        [DataMember(Name="nextId", EmitDefaultValue=false)]
        public string NextId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlertsResponse {\n");
            sb.Append("  Alerts: ").Append(Alerts).Append("\n");
            sb.Append("  NextId: ").Append(NextId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlertsResponse);
        }

        /// <summary>
        /// Returns true if AlertsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AlertsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlertsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Alerts == input.Alerts ||
                    this.Alerts != null &&
                    input.Alerts != null &&
                    this.Alerts.SequenceEqual(input.Alerts)
                ) && 
                (
                    this.NextId == input.NextId ||
                    (this.NextId != null &&
                    this.NextId.Equals(input.NextId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Alerts != null)
                    hashCode = hashCode * 59 + this.Alerts.GetHashCode();
                if (this.NextId != null)
                    hashCode = hashCode * 59 + this.NextId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
