/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Koudenpa.Mackerel.Api.Client.OpenAPIDateConverter;

namespace Koudenpa.Mackerel.Api.Model
{
    /// <summary>
    /// HostStatusRequest
    /// </summary>
    [DataContract]
    public partial class HostStatusRequest :  IEquatable<HostStatusRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Standby for value: standby
            /// </summary>
            [EnumMember(Value = "standby")]
            Standby = 1,

            /// <summary>
            /// Enum Working for value: working
            /// </summary>
            [EnumMember(Value = "working")]
            Working = 2,

            /// <summary>
            /// Enum Maintenance for value: maintenance
            /// </summary>
            [EnumMember(Value = "maintenance")]
            Maintenance = 3,

            /// <summary>
            /// Enum Poweroff for value: poweroff
            /// </summary>
            [EnumMember(Value = "poweroff")]
            Poweroff = 4

        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HostStatusRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HostStatusRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HostStatusRequest" /> class.
        /// </summary>
        /// <param name="status">status (required).</param>
        public HostStatusRequest(StatusEnum status = default(StatusEnum))
        {
            this.Status = status;
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HostStatusRequest {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HostStatusRequest);
        }

        /// <summary>
        /// Returns true if HostStatusRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of HostStatusRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HostStatusRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
