/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Koudenpa.Mackerel.Api.Client;
using Koudenpa.Mackerel.Api.Model;

namespace Koudenpa.Mackerel.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHostApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>HostResponse</returns>
        HostResponse GetHost (string hostId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>ApiResponse of HostResponse</returns>
        ApiResponse<HostResponse> GetHostWithHttpInfo (string hostId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>HostsResponse</returns>
        HostsResponse GetHosts (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>ApiResponse of HostsResponse</returns>
        ApiResponse<HostsResponse> GetHostsWithHttpInfo (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>ApiResponse</returns>
        ApiResponse PostHostStatus (string hostId, HostStatusRequest hostStatus);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>ApiResponse of ApiResponse</returns>
        ApiResponse<ApiResponse> PostHostStatusWithHttpInfo (string hostId, HostStatusRequest hostStatus);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHostApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>Task of HostResponse</returns>
        System.Threading.Tasks.Task<HostResponse> GetHostAsync (string hostId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>Task of ApiResponse (HostResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<HostResponse>> GetHostAsyncWithHttpInfo (string hostId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>Task of HostsResponse</returns>
        System.Threading.Tasks.Task<HostsResponse> GetHostsAsync (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>Task of ApiResponse (HostsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<HostsResponse>> GetHostsAsyncWithHttpInfo (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse> PostHostStatusAsync (string hostId, HostStatusRequest hostStatus);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponse>> PostHostStatusAsyncWithHttpInfo (string hostId, HostStatusRequest hostStatus);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHostApi : IHostApiSync, IHostApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class HostApi : IHostApi
    {
        private Koudenpa.Mackerel.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="HostApi"/> class.
        /// </summary>
        /// <returns></returns>
        public HostApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HostApi"/> class.
        /// </summary>
        /// <returns></returns>
        public HostApi(String basePath)
        {
            this.Configuration = Koudenpa.Mackerel.Api.Client.Configuration.MergeConfigurations(
                Koudenpa.Mackerel.Api.Client.GlobalConfiguration.Instance,
                new Koudenpa.Mackerel.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Koudenpa.Mackerel.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Koudenpa.Mackerel.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Koudenpa.Mackerel.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HostApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public HostApi(Koudenpa.Mackerel.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Koudenpa.Mackerel.Api.Client.Configuration.MergeConfigurations(
                Koudenpa.Mackerel.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Koudenpa.Mackerel.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Koudenpa.Mackerel.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Koudenpa.Mackerel.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HostApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public HostApi(Koudenpa.Mackerel.Api.Client.ISynchronousClient client,Koudenpa.Mackerel.Api.Client.IAsynchronousClient asyncClient, Koudenpa.Mackerel.Api.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Koudenpa.Mackerel.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Koudenpa.Mackerel.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Koudenpa.Mackerel.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Koudenpa.Mackerel.Api.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Koudenpa.Mackerel.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>HostResponse</returns>
        public HostResponse GetHost (string hostId)
        {
             Koudenpa.Mackerel.Api.Client.ApiResponse<HostResponse> localVarResponse = GetHostWithHttpInfo(hostId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>ApiResponse of HostResponse</returns>
        public Koudenpa.Mackerel.Api.Client.ApiResponse< HostResponse > GetHostWithHttpInfo (string hostId)
        {
            // verify the required parameter 'hostId' is set
            if (hostId == null)
                throw new Koudenpa.Mackerel.Api.Client.ApiException(400, "Missing required parameter 'hostId' when calling HostApi->GetHost");

            Koudenpa.Mackerel.Api.Client.RequestOptions localVarRequestOptions = new Koudenpa.Mackerel.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Koudenpa.Mackerel.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Koudenpa.Mackerel.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (hostId != null)
                localVarRequestOptions.PathParameters.Add("hostId", Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< HostResponse >("/hosts/{hostId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetHost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>Task of HostResponse</returns>
        public async System.Threading.Tasks.Task<HostResponse> GetHostAsync (string hostId)
        {
             Koudenpa.Mackerel.Api.Client.ApiResponse<HostResponse> localVarResponse = await GetHostAsyncWithHttpInfo(hostId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <returns>Task of ApiResponse (HostResponse)</returns>
        public async System.Threading.Tasks.Task<Koudenpa.Mackerel.Api.Client.ApiResponse<HostResponse>> GetHostAsyncWithHttpInfo (string hostId)
        {
            // verify the required parameter 'hostId' is set
            if (hostId == null)
                throw new Koudenpa.Mackerel.Api.Client.ApiException(400, "Missing required parameter 'hostId' when calling HostApi->GetHost");


            Koudenpa.Mackerel.Api.Client.RequestOptions localVarRequestOptions = new Koudenpa.Mackerel.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (hostId != null)
                localVarRequestOptions.PathParameters.Add("hostId", Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<HostResponse>("/hosts/{hostId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetHost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>HostsResponse</returns>
        public HostsResponse GetHosts (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string))
        {
             Koudenpa.Mackerel.Api.Client.ApiResponse<HostsResponse> localVarResponse = GetHostsWithHttpInfo(service, role, name, status, customIdentifier);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>ApiResponse of HostsResponse</returns>
        public Koudenpa.Mackerel.Api.Client.ApiResponse< HostsResponse > GetHostsWithHttpInfo (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string))
        {
            Koudenpa.Mackerel.Api.Client.RequestOptions localVarRequestOptions = new Koudenpa.Mackerel.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Koudenpa.Mackerel.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Koudenpa.Mackerel.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (service != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "service", service))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (role != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "role", role))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (name != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "name", name))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (status != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "status", status))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (customIdentifier != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "customIdentifier", customIdentifier))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< HostsResponse >("/hosts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetHosts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>Task of HostsResponse</returns>
        public async System.Threading.Tasks.Task<HostsResponse> GetHostsAsync (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string))
        {
             Koudenpa.Mackerel.Api.Client.ApiResponse<HostsResponse> localVarResponse = await GetHostsAsyncWithHttpInfo(service, role, name, status, customIdentifier);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="service">optional サービス名。 (optional)</param>
        /// <param name="role">サービス内のロール名。複数指定可能（結果は各ロールに所属するホスト群の和集合となります）。serviceが指定されていない場合は無効です。 (optional)</param>
        /// <param name="name">optional ホスト名。 (optional)</param>
        /// <param name="status">optional ホストのステータスを絞り込む。複数指定可能。デフォルトは working と standbyです。 (optional)</param>
        /// <param name="customIdentifier">optional ホスト情報の登録やホスト情報の更新で登録したユーザー独自の識別子。 (optional)</param>
        /// <returns>Task of ApiResponse (HostsResponse)</returns>
        public async System.Threading.Tasks.Task<Koudenpa.Mackerel.Api.Client.ApiResponse<HostsResponse>> GetHostsAsyncWithHttpInfo (string service = default(string), string role = default(string), string name = default(string), string status = default(string), string customIdentifier = default(string))
        {

            Koudenpa.Mackerel.Api.Client.RequestOptions localVarRequestOptions = new Koudenpa.Mackerel.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (service != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "service", service))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (role != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "role", role))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (name != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "name", name))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (status != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "status", status))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (customIdentifier != null)
            {
                foreach (var _kvp in Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToMultiMap("", "customIdentifier", customIdentifier))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<HostsResponse>("/hosts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetHosts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>ApiResponse</returns>
        public ApiResponse PostHostStatus (string hostId, HostStatusRequest hostStatus)
        {
             Koudenpa.Mackerel.Api.Client.ApiResponse<ApiResponse> localVarResponse = PostHostStatusWithHttpInfo(hostId, hostStatus);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>ApiResponse of ApiResponse</returns>
        public Koudenpa.Mackerel.Api.Client.ApiResponse< ApiResponse > PostHostStatusWithHttpInfo (string hostId, HostStatusRequest hostStatus)
        {
            // verify the required parameter 'hostId' is set
            if (hostId == null)
                throw new Koudenpa.Mackerel.Api.Client.ApiException(400, "Missing required parameter 'hostId' when calling HostApi->PostHostStatus");

            // verify the required parameter 'hostStatus' is set
            if (hostStatus == null)
                throw new Koudenpa.Mackerel.Api.Client.ApiException(400, "Missing required parameter 'hostStatus' when calling HostApi->PostHostStatus");

            Koudenpa.Mackerel.Api.Client.RequestOptions localVarRequestOptions = new Koudenpa.Mackerel.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Koudenpa.Mackerel.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Koudenpa.Mackerel.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (hostId != null)
                localVarRequestOptions.PathParameters.Add("hostId", Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.Data = hostStatus;

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post< ApiResponse >("/hosts/{hostId}/status", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostHostStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse> PostHostStatusAsync (string hostId, HostStatusRequest hostStatus)
        {
             Koudenpa.Mackerel.Api.Client.ApiResponse<ApiResponse> localVarResponse = await PostHostStatusAsyncWithHttpInfo(hostId, hostStatus);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Koudenpa.Mackerel.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId"></param>
        /// <param name="hostStatus"></param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        public async System.Threading.Tasks.Task<Koudenpa.Mackerel.Api.Client.ApiResponse<ApiResponse>> PostHostStatusAsyncWithHttpInfo (string hostId, HostStatusRequest hostStatus)
        {
            // verify the required parameter 'hostId' is set
            if (hostId == null)
                throw new Koudenpa.Mackerel.Api.Client.ApiException(400, "Missing required parameter 'hostId' when calling HostApi->PostHostStatus");

            // verify the required parameter 'hostStatus' is set
            if (hostStatus == null)
                throw new Koudenpa.Mackerel.Api.Client.ApiException(400, "Missing required parameter 'hostStatus' when calling HostApi->PostHostStatus");


            Koudenpa.Mackerel.Api.Client.RequestOptions localVarRequestOptions = new Koudenpa.Mackerel.Api.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (hostId != null)
                localVarRequestOptions.PathParameters.Add("hostId", Koudenpa.Mackerel.Api.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.Data = hostStatus;

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ApiResponse>("/hosts/{hostId}/status", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostHostStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
