/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing Alert
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlertTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Alert
        //private Alert instance;

        public AlertTests()
        {
            // TODO uncomment below to create an instance of Alert
            //instance = new Alert();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Alert
        /// </summary>
        [Fact]
        public void AlertInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Alert
            //Assert.IsInstanceOfType<Alert> (instance, "variable 'instance' is a Alert");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'MonitorId'
        /// </summary>
        [Fact]
        public void MonitorIdTest()
        {
            // TODO unit test for the property 'MonitorId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'HostId'
        /// </summary>
        [Fact]
        public void HostIdTest()
        {
            // TODO unit test for the property 'HostId'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'OpenedAt'
        /// </summary>
        [Fact]
        public void OpenedAtTest()
        {
            // TODO unit test for the property 'OpenedAt'
        }
        /// <summary>
        /// Test the property 'ClosedAt'
        /// </summary>
        [Fact]
        public void ClosedAtTest()
        {
            // TODO unit test for the property 'ClosedAt'
        }

    }

}
