/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing AlertsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlertsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlertsResponse
        //private AlertsResponse instance;

        public AlertsResponseTests()
        {
            // TODO uncomment below to create an instance of AlertsResponse
            //instance = new AlertsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlertsResponse
        /// </summary>
        [Fact]
        public void AlertsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertsResponse
            //Assert.IsInstanceOfType<AlertsResponse> (instance, "variable 'instance' is a AlertsResponse");
        }


        /// <summary>
        /// Test the property 'Alerts'
        /// </summary>
        [Fact]
        public void AlertsTest()
        {
            // TODO unit test for the property 'Alerts'
        }
        /// <summary>
        /// Test the property 'NextId'
        /// </summary>
        [Fact]
        public void NextIdTest()
        {
            // TODO unit test for the property 'NextId'
        }

    }

}
