/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing ApiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiResponse
        //private ApiResponse instance;

        public ApiResponseTests()
        {
            // TODO uncomment below to create an instance of ApiResponse
            //instance = new ApiResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiResponse
        /// </summary>
        [Fact]
        public void ApiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponse
            //Assert.IsInstanceOfType<ApiResponse> (instance, "variable 'instance' is a ApiResponse");
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
