/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing Host
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Host
        //private Host instance;

        public HostTests()
        {
            // TODO uncomment below to create an instance of Host
            //instance = new Host();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Host
        /// </summary>
        [Fact]
        public void HostInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Host
            //Assert.IsInstanceOfType<Host> (instance, "variable 'instance' is a Host");
        }


        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'CustomIdentifier'
        /// </summary>
        [Fact]
        public void CustomIdentifierTest()
        {
            // TODO unit test for the property 'CustomIdentifier'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'Interfaces'
        /// </summary>
        [Fact]
        public void InterfacesTest()
        {
            // TODO unit test for the property 'Interfaces'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Fact]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'IsRetired'
        /// </summary>
        [Fact]
        public void IsRetiredTest()
        {
            // TODO unit test for the property 'IsRetired'
        }
        /// <summary>
        /// Test the property 'RetiredAt'
        /// </summary>
        [Fact]
        public void RetiredAtTest()
        {
            // TODO unit test for the property 'RetiredAt'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
