/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing HostStatusRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostStatusRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostStatusRequest
        //private HostStatusRequest instance;

        public HostStatusRequestTests()
        {
            // TODO uncomment below to create an instance of HostStatusRequest
            //instance = new HostStatusRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostStatusRequest
        /// </summary>
        [Fact]
        public void HostStatusRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HostStatusRequest
            //Assert.IsInstanceOfType<HostStatusRequest> (instance, "variable 'instance' is a HostStatusRequest");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
