/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing HostMetricValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostMetricValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostMetricValue
        //private HostMetricValue instance;

        public HostMetricValueTests()
        {
            // TODO uncomment below to create an instance of HostMetricValue
            //instance = new HostMetricValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostMetricValue
        /// </summary>
        [Fact]
        public void HostMetricValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HostMetricValue
            //Assert.IsInstanceOfType<HostMetricValue> (instance, "variable 'instance' is a HostMetricValue");
        }


        /// <summary>
        /// Test the property 'HostId'
        /// </summary>
        [Fact]
        public void HostIdTest()
        {
            // TODO unit test for the property 'HostId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
