/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing HostsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostsResponse
        //private HostsResponse instance;

        public HostsResponseTests()
        {
            // TODO uncomment below to create an instance of HostsResponse
            //instance = new HostsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostsResponse
        /// </summary>
        [Fact]
        public void HostsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HostsResponse
            //Assert.IsInstanceOfType<HostsResponse> (instance, "variable 'instance' is a HostsResponse");
        }


        /// <summary>
        /// Test the property 'Hosts'
        /// </summary>
        [Fact]
        public void HostsTest()
        {
            // TODO unit test for the property 'Hosts'
        }

    }

}
