/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Koudenpa.Mackerel.Api.Api;
using Koudenpa.Mackerel.Api.Model;
using Koudenpa.Mackerel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Koudenpa.Mackerel.Api.Test
{
    /// <summary>
    ///  Class for testing HostResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostResponse
        //private HostResponse instance;

        public HostResponseTests()
        {
            // TODO uncomment below to create an instance of HostResponse
            //instance = new HostResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostResponse
        /// </summary>
        [Fact]
        public void HostResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HostResponse
            //Assert.IsInstanceOfType<HostResponse> (instance, "variable 'instance' is a HostResponse");
        }


        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }

    }

}
