name: Publish pages

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build
      run: dotnet publish -c Release

    - name: Clear dist
      run: rm -rf ./docs
    - name: Copy dist
      run: mv ./bin/Release/netstandard2.1/publish/bazor-app-sandbox/dist ./docs

    - name: Commit & Push
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          SSH_DIR="${HOME}/.ssh"
          mkdir "${SSH_DIR}"
          ssh-keyscan -t rsa github.com > "${SSH_DIR}/known_hosts"
          echo "${ACTIONS_DEPLOY_KEY}" > "${SSH_DIR}/id_rsa"
          chmod 400 "${SSH_DIR}/id_rsa"

          git remote set-url origin "git@github.com:${GITHUB_REPOSITORY}.git"
          git config --global user.name "7474"
          git config --global user.email "koudenpa@hotmail.com"

          git add ./docs
          git commit -m 'Pulish pages.'
          git push origin HEAD:master
        else
          echo "No change"
        fi
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}